services:
  - type: web
    name: coffee-inventory-system
    env: php
    plan: free
    region: singapore
    buildCommand: |
      composer install
      php artisan key:generate
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
